//! This module renders the financial performance visualization.
//!
//! It transforms a time-series of `Report` snapshots into a bar chart,
//! allowing users to visually track their savings balance month-by-month.

use egui::Ui;
use egui_plot::{Bar, BarChart, Plot};

use crate::report::report::Report;

/// Renders a bar chart representing the financial balance over the simulation horizon.
///
/// # Arguments
/// * `ui` - The `egui::Ui` context.
/// * `reports` - A slice of `Report` snapshots generated by the simulation engine.
pub fn render(ui: &mut Ui, reports: &[Report]) {
    // Map each report to a bar representing the balance at that month.
    let bars: Vec<Bar> = reports
        .iter()
        .map(|report| Bar::new(report.month as f64, report.savings))
        .collect();

    // Configure the chart style.
    let chart = BarChart::new("Char", bars).width(0.6);

    // Initialize the plot container.
    Plot::new("savings_chart")
        .height(300.0)
        .show_grid(false)
        .show_axes([true, true])
        .x_axis_label("Month")
        .y_axis_label("Balance")
        .allow_scroll(false)
        .show_background(false)
        .y_axis_formatter(|grid_mark, _max_chars| format!("{:.0}", grid_mark.value))
        .show(ui, |plot_ui| {
            plot_ui.bar_chart(chart);
        });
}
