//! This module renders a detailed tabular view of the simulation results.
//!
//! It displays a month-by-month breakdown of financial performance,
//! including savings accumulation, total incomes, expenses, and loan impacts.

use egui::Ui;

use crate::report::report::Report;

/// Renders a scrollable grid of simulation data.
///
/// # Arguments
/// * `ui` - The `egui::Ui` context.
/// * `reports` - A slice of `Report` snapshots generated by the simulation engine.
pub fn render(ui: &mut Ui, reports: &[Report]) {
    // Wrap the grid in a ScrollArea to handle cases where the simulation
    // horizon is long.
    egui::ScrollArea::vertical().show(ui, |ui| {
        egui::Grid::new("report_table")
            .striped(true)
            .show(ui, |ui| {
                // Table Header.
                ui.label("Month");
                ui.label("Savings");
                ui.label("Incomes");
                ui.label("Expenses");
                ui.label("Loans");
                ui.end_row();

                // Table Body.
                for report in reports {
                    ui.label(report.month.to_string());
                    ui.label(format!("{:.0}", report.savings));
                    ui.label(format!("{:.0}", report.incomes));
                    ui.label(format!("{:.0}", report.expenses));
                    ui.label(format!("{:.0}", report.loans));
                    ui.end_row();
                }
            });
    });
}
